services:
  test-server:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: server-test
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - TEST_PATH=tests/server/**/*.test.ts
    command: npm run docker-test