services:
  client:
    build:
      context: ./app/client
      dockerfile: Dockerfile.dev
    container_name: client
    volumes:
      - ./app/client:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    command: npm run dev
    depends_on:
      - server
  server:
    build:
      context: ./app/server
      dockerfile: Dockerfile.dev
    container_name: server
    volumes:
      - ./app/server:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app
  mysql:
    image: mysql:9
    container_name: mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  app:
    driver: bridge
