services:
  test-server:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: server-test
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      TEST_PATH: ${TEST_PATH}
    command: npm run docker-test $TEST_PATH
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app
  mysql:
    image: mysql:9
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  app:
    driver: bridge