FROM node:alpine3.20 AS build

WORKDIR /app

ARG VITE_API

ENV VITE_API=${VITE_API}

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:1.27.3-alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]