definition:
  swagger: "2.0"
  info:
    title: 'Hide and Secret API'
    version: 1.0.0
    description: 'Hide and Secret API docs'
  servers:
    - url: "{{BASE_URL}}"
  securityDefinitions:
    bearerAuth:
      type: "apiKey"
      in: "header"
      name: "Authorization"
      description: "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\""
  security:
    - bearerAuth: []
apis:
  - './routes/api/*.ts'