name: Build, Push, and Deploy to ECS

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        cd app/client
        npm install
        cd ../server
        npm install

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push client image
      run: |
        cd app/client
        docker build -f Dockerfile.prod \
          --build-arg VITE_API=${{ secrets.VITE_API_STAGING }} \
          -t amagalla24/hide-and-secret-client:latest .
        docker push amagalla24/hide-and-secret-client:latest

    - name: Build and push server image
      run: |
        cd app/server
        docker build -f Dockerfile.prod \
          -t amagalla24/hide-and-secret-server:latest .
        docker push amagalla24/hide-and-secret-server:latest

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
        aws-region: us-east-1

    - name: Register new ECS task definition
      run: |
        # Update image references in task definition file
        sed -i 's|amagalla24/hide-and-secret-server:latest|amagalla24/hide-and-secret-server:latest|g' ecs-task-definition.json
        sed -i 's|amagalla24/hide-and-secret-client:latest|amagalla24/hide-and-secret-client:latest|g' ecs-task-definition.json

        # Register the task definition with ECS
        aws ecs register-task-definition \
          --cli-input-json file://ecs-task-definition.json

    - name: Update ECS service with new task definition
      run: |
        # Get the latest task definition revision
        task_definition=$(aws ecs describe-task-definition --task-definition HideAndSecret-staging --query 'taskDefinition.taskDefinitionArn' --output text)

        # Update ECS service with the new task definition
        aws ecs update-service \
          --cluster StagingHideAndSecretCluster \
          --service HideAndSecret-staging \
          --task-definition $task_definition \
          --force-new-deployment